# ----------------------------------------------------
# DECAP CMS CONFIGURATION FOR STARSHIP PORTFOLIO
# ----------------------------------------------------

# --- Backend Configuration (GitHub OAuth) ---
backend:
  name: github
  repo: owner-scotthwcouk/owner-scotthwcouk.github.io
  branch: main
  base_url: https://github.com
  auth_endpoint: /api/v1/auth
  site_url: https://owner-scotthwcouk.github.io/owner-scotthwcouk.github.io-master/ # From package.json homepage
  auth_scope: repo # Required for committing changes

# --- User Interface Configuration ---
publish_mode: editorial_workflow # Recommended for review/drafts
media_folder: "public/Media" # The directory where uploaded images/files will be saved
public_folder: "/Media" # The base path for accessing the files

# --- Collections Configuration (Mapping to data.json) ---
collections:
  - name: "content_management"
    label: "Starfleet Content Modules"
    editor:
      preview: false # Disable live preview for simplicity

    files:
      # 1. Mission Logs (Projects) Collection
      - label: "1. Mission Logs (Projects)"
        name: "projects_collection"
        file: "public/content/data.json"
        description: "Add, update, or delete entries from the Mission Logs section."
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            collapsed: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Stardate"
                name: "stardate"
                widget: "string"
              - label: "Summary"
                name: "summary"
                widget: "markdown"
              - label: "GitHub URL"
                name: "url"
                widget: "string"
              - label: "Details/Execution Summary (Optional)"
                name: "details"
                widget: "list"
                collapsed: true
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "string"
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    field: {label: "Item Text", name: "item_text", widget: "string"}

      # 2. Mission Updates Collection
      - label: "2. Mission Updates (Study Directives)"
        name: "mission_updates_collection"
        file: "public/content/data.json"
        description: "Update the academic progress and current directives."
        fields:
          - label: "Mission Updates"
            name: "mission_update"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - label: "Updates Log"
                name: "updates"
                widget: "list"
                fields:
                  - {label: "Stardate", name: "stardate", widget: "string"}
                  - {label: "Update Text", name: "text", widget: "string"}
              - label: "Directives"
                name: "directives"
                widget: "list"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Intro Text", name: "text", widget: "string"}
                  - label: "Items List"
                    name: "items"
                    widget: "list"
                    field: {label: "Directive Detail", name: "item_text", widget: "string"}
    
      # 3. Starfleet Protocols (Policies) Collection
      - label: "3. Starfleet Protocols (Policies)"
        name: "protocols_collection"
        file: "public/content/data.json"
        description: "Edit the text content for the Privacy Policy and Terms of Use."
        fields:
          - label: "Protocols"
            name: "protocols"
            widget: "object"
            fields:
              - label: "Privacy Policy"
                name: "privacy"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Effective Date", name: "effective_date", widget: "string"}
                  - label: "Sections"
                    name: "sections"
                    widget: "list"
                    fields:
                      - {label: "Section Heading", name: "heading", widget: "string"}
                      - {label: "Content Type", name: "type", widget: "select", options: ["paragraph", "list"]}
                      - {label: "Text (if paragraph)", name: "text", widget: "markdown", required: false}
                      - label: "List Items (if list)"
                        name: "items"
                        widget: "list"
                        field: {label: "Item", name: "item", widget: "string", required: false}
              - label: "Terms of Use"
                name: "terms"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Effective Date", name: "effective_date", widget: "string"}
                  - label: "Sections"
                    name: "sections"
                    widget: "list"
                    fields:
                      - {label: "Section Heading", name: "heading", widget: "string"}
                      - {label: "Content Type", name: "type", widget: "select", options: ["paragraph", "list"]}
                      - {label: "Intro Text (if list)", name: "intro", widget: "string", required: false}
                      - {label: "Text (if paragraph)", name: "text", widget: "markdown", required: false}
                      - label: "List Items (if list)"
                        name: "items"
                        widget: "list"
                        field: {label: "Item", name: "item", widget: "string", required: false}
