# ----------------------------------------------------
# DECAP CMS CONFIGURATION FOR STARSHIP PORTFOLIO
# ----------------------------------------------------

# --- Backend Configuration (Netlify Git Gateway) ---
backend:
  name: git-gateway # Uses Netlify's built-in Git authentication service
  branch: main      # The branch to commit content changes to

# --- User Interface Configuration ---
publish_mode: editorial_workflow # Allows for draft/review workflow before publishing
media_folder: "public/Media"     # The directory where uploaded images/files will be saved
public_folder: "/Media"          # The base path for accessing the files

# --- Collections Configuration (Mapping to data.json) ---
collections:
  - name: "content_management"
    label: "Starfleet Content Modules"
    editor:
      preview: false # Disable live preview for simplicity

    files:
      # This file section MUST match the path where you saved data.json
      - label: "Starfleet Manifests (data.json)"
        name: "data_file"
        file: "public/content/data.json" 
        description: "Central data manifest for the portfolio sections."
        fields:
          # --- Field structure for data.json ---
          
          # 1. About Section (Object)
          - label: "1. Personal Bio (About)"
            name: "about"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Profile Image URL", name: "image", widget: "string"}
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: {label: "Text", name: "text", widget: "markdown"}

          # 2. Projects Section (List)
          - label: "2. Mission Logs (Projects)"
            name: "projects"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Stardate", name: "stardate", widget: "string"}
              - {label: "Summary", name: "summary", widget: "markdown"}
              - {label: "GitHub URL", name: "url", widget: "string"}
              - label: "Details/Execution Summary (Optional)"
                name: "details"
                widget: "list"
                collapsed: true
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    field: {label: "Item Text", name: "item_text", widget: "string"}

          # 3. Mission Update Section (Object)
          - label: "3. Mission Updates (Study Directives)"
            name: "mission_update"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - label: "Updates Log"
                name: "updates"
                widget: "list"
                fields:
                  - {label: "Stardate", name: "stardate", widget: "string"}
                  - {label: "Update Text", name: "text", widget: "string"}
              - label: "Directives"
                name: "directives"
                widget: "list"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Intro Text", name: "text", widget: "string"}
                  - label: "Items List"
                    name: "items"
                    widget: "list"
                    field: {label: "Directive Detail", name: "item_text", widget: "string"}
          
          # 4. Protocols Section (Object) - Used for Policies
          - label: "4. Starfleet Protocols (Policies)"
            name: "protocols"
            widget: "object"
            fields:
              - label: "Privacy Policy"
                name: "privacy"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Effective Date", name: "effective_date", widget: "string"}
                  - label: "Sections"
                    name: "sections"
                    widget: "list"
                    fields:
                      - {label: "Section Heading", name: "heading", widget: "string"}
                      - {label: "Content Type", name: "type", widget: "select", options: ["paragraph", "list"]}
                      - {label: "Text (if paragraph)", name: "text", widget: "markdown", required: false}
                      - label: "List Items (if list)"
                        name: "items"
                        widget: "list"
                        field: {label: "Item", name: "item", widget: "string", required: false}
              - label: "Terms of Use"
                name: "terms"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Effective Date", name: "effective_date", widget: "string"}
                  - label: "Sections"
                    name: "sections"
                    widget: "list"
                    fields:
                      - {label: "Section Heading", name: "heading", widget: "string"}
                      - {label: "Content Type", name: "type", widget: "select", options: ["paragraph", "list"]}
                      - {label: "Intro Text (if list)", name: "intro", widget: "string", required: false}
                      - {label: "Text (if paragraph)", name: "text", widget: "markdown", required: false}
                      - label: "List Items (if list)"
                        name: "items"
                        widget: "list"
                        field: {label: "Item", name: "item", widget: "string", required: false}





                        
